version: "3.6"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "cd /var/www/html/trial; composer install; npm install; php artisan serve --host=0.0.0.0"
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:8000"

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mnt/database/data:/var/lib/mysql
    - ./mnt/database/sql:/docker-entrypoint-initdb.d
    ports:
    - 13306:3306
